title: Robotics arXiv Daily
description: 每日自动更新的机器人领域 arXiv 论文速递 (Manipulation, World Model, Humanoid, etc.)
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag

#不仅启用 kramdown，还配置它自动生成 header ID，方便目录跳转
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3

# 显式设置 GitHub Pages 的一些变量，防止构建错误
url: "" 
# baseurl: "/arxiv-daily" # 如果您的仓库名不是 robotics-arxiv-daily，请改为您的仓库名，或者直接删掉这一行（如果有自定义域名）